### ISSUE TITLE
undefined reference to `fs_config'

### ISSUE THREAD

**Issue by rockyrays** [pbatard/bootimg-tools#7]
gcc mkbootfs.c  -o mkbootfs -I../include

/tmp/ccHBJe3S.o: In function `fix_stat':

mkbootfs.c:(.text+0x247): undefined reference to `fs_config'

collect2: error: ld returned 1 exit status

**Comment by dje4321** [comment]
Im also having this issue

**Comment by kkroening** [comment]
You need `libcutils`.

Source code: https://github.com/android/platform_system_core/tree/master/libcutils

Ubuntu install: `sudo apt-get install android-libcutils-dev`.  This install `libcutils.so` in `/usr/lib/android`.  Unfortunately it doesn't contain a static library, so you have to build against the `.so` and then make sure it's on your `$LD_LIBRARY_PATH` when you run the built `mkbootfs`:

```
gcc mkbootfs.c -o mkbootfs -I../include -lcutils -L/usr/lib/android/
LD_LIBRARY_PATH=/usr/lib/android ./mkbootfs
```

Yuck! But at least it builds.

Ideally `android-libcutils-dev` would contain a static library that could be linked, but unfortunately you're either stuck with the `.so` or building `libcutils` yourself from the `platform_system_core` link posted above. I have no idea how to build `libcutils` as a static library from source, and at that point you might as well use the version of `mkbootfs` that's part of that project, since it's basically the same thing as what's in this fork.

In case you came to this issue from [Building and booting Nexus 5 kernel](http://marcin.jabrzyk.eu/posts/2014/05/building-and-booting-nexus-5-kernel), the instructions there tell you to build `mkbootfs`, but as far as I can tell it's not actually necessary. Just skip that step and you should be in business.

**Comment by kkroening** [comment]
I honestly don't know why `mkbootfs` is in this project. It doesn't build as part of the Makefile and it doesn't seem to be significantly different from the one in `platform_system_core`. Perhaps it should just be removed?

**Comment by pbatard** [comment]
I am no longer planning on maintaining this project. As such I will close this issue.
If you require updates, I will kindly ask that you create or find a fork, and request it there.
